package com.clueride.domain.path;

/**
 * Persistence layer for LinkPath records.
 *
 * These are how we setup the Path records that connect two Attractions
 * for a given Course.
 */
public interface LinkPathStore {
    /**
     * Given the data for a new {@link LinkPath}, create a new record
     * and assign a unique key for that record.
     *
     * @param linkPathEntity {@link LinkPath} instance to create.
     * @return same instance with the ID generated by the DB.
     */
    LinkPathEntity createNew(LinkPathEntity linkPathEntity);
}
