package com.clueride.domain.path.meta;

/**
 * Persistence layer for PathMeta records.
 *
 * These are how we setup the Path records that connect two Attractions
 * for a given Course.
 */
public interface PathMetaStore {
    /**
     * Retrieve instance of PathMeta matching the given ID.
     *
     * @param pathId unique identifier for the Path.
     * @return instance of PathMetaEntity.
     */
    PathMetaEntity get(Integer pathId);

    /**
     * Given the data for a new {@link PathMeta}, create a new record
     * and assign a unique key for that record.
     *
     * @param pathMetaEntity {@link PathMeta} instance to create.
     * @return same instance with the ID generated by the DB.
     */
    PathMetaEntity createNew(PathMetaEntity pathMetaEntity);

    /**
     * Finds a Path that links between a pair of AttractionIDs.
     *
     * The direction is significant (but should it be?).
     *
     * @param startId  Starting Attraction ID.
     * @param endId Ending Attraction ID.
     * @return First matching PathMeta record.
     */
    PathMetaEntity findSuitablePath(Integer startId, Integer endId);

}
