package com.clueride.domain.path.meta;

/**
 * Persistence layer for PathMeta records.
 *
 * These are how we setup the Path records that connect two Attractions
 * for a given Course.
 */
public interface PathMetaStore {
    /**
     * Given the data for a new {@link PathMeta}, create a new record
     * and assign a unique key for that record.
     *
     * @param pathMetaEntity {@link PathMeta} instance to create.
     * @return same instance with the ID generated by the DB.
     */
    PathMetaEntity createNew(PathMetaEntity pathMetaEntity);
}
